import React from 'react';
import { View, Text, StyleSheet, TouchableOpacity, ScrollView } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { FontAwesome } from '@expo/vector-icons';

const PrivacyPolicyScreen = ({ navigation }: any) => {
  return (
    <SafeAreaView style={styles.container}>
      {/* Header */}
      <View style={styles.header}>
        <TouchableOpacity onPress={() => navigation.goBack()}>
          <FontAwesome name="arrow-left" size={20} color="#333" />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Privacy Policy</Text>
        <View style={{ width: 20 }} />
      </View>

      {/* Content */}
      <ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
        <Text style={styles.title}>Ride Andhra — Privacy Policy</Text>
        <Text style={styles.updateDate}>Effective date: January 8, 2026</Text>

        <Text style={styles.sectionTitle}>1. Introduction</Text>
        <Text style={styles.paragraph}>
          Ride Andhra (“we”, “us”, “the App”) is a mobile/information service that provides ride information, route and fare estimates, and driver contact details. This Privacy Policy explains what information we collect, why we collect it, how we use it, how long we keep it, and the choices you have. By using Ride Andhra, you agree to the terms of this Privacy Policy.
        </Text>

        <Text style={styles.sectionTitle}>2. Key points — quick summary</Text>
        <Text style={styles.paragraph}>
          • We do not collect, store, or process users’ photos or biometric data.{'\n\n'}
          • The App collects only the information necessary to provide ride search and estimated fares: user name and the pickup and drop-off locations the user selects.{'\n\n'}
          • Ride Andhra does not process payments, host wallets, operate referral/commission payment mechanisms, or store financial information. All fare information provided is an estimate only.{'\n\n'}
          • Bookings and payments (if any) occur outside the App between the rider and the driver or a third-party service; Ride Andhra is an information-only service.{'\n\n'}
          • For questions or data requests contact: help.rideandhra@gmail.com or +91 83749 50475 (Customer Care).
        </Text>

        <Text style={styles.sectionTitle}>3. Information we collect</Text>
        <Text style={styles.subSectionTitle}>Information you provide directly</Text>
        <Text style={styles.paragraph}>
          • **Name:** If you choose to enter a name when using the App.{'\n\n'}
          • **Pickup and drop-off locations:** Explicit locations selected by you to obtain route information and fare estimates.{'\n\n'}
          • **Optional fields:** If you provide any other optional information within the App (e.g., comments), those fields will be treated according to the same retention and disclosure rules below.
        </Text>
        <Text style={styles.subSectionTitle}>Technical and usage data (automatically collected)</Text>
        <Text style={styles.paragraph}>
          • **Device and connection information:** device model, operating system version, app version, IP address, and mobile network information.{'\n\n'}
          • **Usage data:** timestamps, logs of interactions with the App (for debugging, troubleshooting and product improvement), crash reports.{'\n\n'}
          This technical data is collected to operate, secure, and improve the App and to diagnose problems.
        </Text>

        <Text style={styles.sectionTitle}>4. How we use the information</Text>
        <Text style={styles.paragraph}>
          We use the information we collect for the following purposes:{'\n\n'}
          • To provide the core service: show route, driver details (if applicable), and produce estimated fares based on selected pickup/drop-off.{'\n\n'}
          • To operate, maintain, and improve the App, including debugging and analytics.{'\n\n'}
          • To respond to support requests and communications from users.{'\n\n'}
          • To comply with legal obligations (e.g., lawful requests) when required.{'\n\n'}
          **Important:** The App provides only estimated fares generated by an internal algorithm that considers selected locations and route distance. These are estimates only and not a bill or offer to collect payment. We do not accept, process, or store payments, nor do we provide a wallet or payment gateway within the App.
        </Text>

        <Text style={styles.sectionTitle}>5. When and with whom we share data</Text>
        <Text style={styles.paragraph}>
          We do not sell personal data. We may share user information in the following limited circumstances:{'\n\n'}
          • **Service providers:** with trusted third-party vendors who perform services on our behalf (e.g., hosting, analytics, mapping APIs). These vendors are contractually restricted to use data only to provide services to us.{'\n\n'}
          • **Legal obligations:** when required by law, regulation, or valid legal process, or to respond to lawful requests from public authorities (including to meet national security or law enforcement requirements).{'\n\n'}
          • **Safety and fraud prevention:** where necessary to detect, prevent, and address fraud, security or technical issues, or to protect rights, property or safety of users or the public.{'\n\n'}
          If you use mapping or third-party features, those providers may collect location or usage data directly under their own privacy policies.
        </Text>

        <Text style={styles.sectionTitle}>6. Data retention</Text>
        <Text style={styles.paragraph}>
          We retain personal information (name and selected pickup/dropoff) only for as long as necessary to provide the service and for the limited period needed for operational, diagnostic, or legal purposes — typically no longer than 12 months unless a longer retention is required or permitted by law.{'\n\n'}
          Technical logs and crash reports may be retained in aggregated or pseudonymized form for product improvement.
        </Text>

        <Text style={styles.sectionTitle}>7. Your choices and rights</Text>
        <Text style={styles.paragraph}>
          Depending on your jurisdiction, you may have rights regarding the personal data we hold about you, such as:{'\n\n'}
          • The right to access and request a copy of the personal data we hold about you.{'\n\n'}
          • The right to correct inaccurate personal data.{'\n\n'}
          • The right to request deletion of your personal data, subject to retention required by law.{'\n\n'}
          • The right to restrict or object to certain processing, where applicable.{'\n\n'}
          To exercise these rights, or for any data privacy requests, contact us at help.rideandhra@gmail.com or +91 83749 50475. We will respond in accordance with applicable law.
        </Text>

        <Text style={styles.sectionTitle}>8. Security</Text>
        <Text style={styles.paragraph}>
          We implement reasonable technical and organizational measures designed to protect personal information from unauthorized access, disclosure, alteration, and destruction. However, no system is completely secure; we cannot guarantee absolute security. If a data security incident affects you, we will follow applicable legal obligations for notifications.
        </Text>

        <Text style={styles.sectionTitle}>9. Children</Text>
        <Text style={styles.paragraph}>
          Ride Andhra is not intended for children under the age of 13. We do not knowingly collect personal data from children under 13. If we learn that we have collected such personal data without parental consent, we will delete it promptly.
        </Text>

        <Text style={styles.sectionTitle}>10. Changes to this Policy</Text>
        <Text style={styles.paragraph}>
          We may update this Privacy Policy to reflect changes in our practices or for legal, technical, or business reasons. When we make material changes, we will post the updated policy in the App with an updated “Effective date.”
        </Text>

        <Text style={styles.sectionTitle}>11. Contact us</Text>
        <Text style={styles.paragraph}>
          For questions about this Privacy Policy, data access requests, or privacy-related concerns:{'\n\n'}
          📧 Email: help.rideandhra@gmail.com{'\n\n'}
          📞 Phone / Customer Care: +91 83749 50475
        </Text>

        <Text style={styles.sectionTitle}>12. Important legal notice regarding taxes and GST</Text>
        <Text style={styles.paragraph}>
          Ride Andhra provides information-only services (route and fare estimates) and does not process payments, operate wallets, or remit fares. I cannot assist in creating documents or strategies intended to avoid taxes or other lawful obligations. Determinations about GST applicability and compliance are legal and tax matters that depend on facts, precise operations, and prevailing law.
        </Text>

        <Text style={{ marginTop: 32, textAlign: 'center', fontSize: 14, color: '#9ca3af' }}>
          © {new Date().getFullYear()} Ride Andhra. All rights reserved.
        </Text>
      </ScrollView>
    </SafeAreaView>
  );
};

// Styles
const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: 'white' },
  header: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    padding: 16, borderBottomWidth: 1, borderBottomColor: '#e5e7eb',
  },
  headerTitle: { fontSize: 20, fontWeight: 'bold' },
  content: { padding: 20 },
  title: { fontSize: 26, fontWeight: 'bold', marginBottom: 8 },
  updateDate: { fontSize: 14, color: '#9ca3af', marginBottom: 24 },
  sectionTitle: { fontSize: 20, fontWeight: 'bold', marginTop: 24, marginBottom: 12, color: '#111827' },
  subSectionTitle: { fontSize: 18, fontWeight: 'bold', marginTop: 16, marginBottom: 8, color: '#374151' },
  paragraph: { fontSize: 16, lineHeight: 24, color: '#374151', textAlign: 'justify' },
});

export default PrivacyPolicyScreen;
